// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAumd4TQCdO-tTZexbIiDmrVd4Bd_ybCKc',
    appId: '1:709046596518:web:6a2f2f02c3857b9d70d567',
    messagingSenderId: '709046596518',
    projectId: 'chuck-firebase',
    authDomain: 'chuck-firebase.firebaseapp.com',
    storageBucket: 'chuck-firebase.appspot.com',
    measurementId: 'G-43EM0S0WTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0HOgH0dW8VsJF-9NK6CScAXtxWSEH58',
    appId: '1:709046596518:android:189f21adf4e01ec370d567',
    messagingSenderId: '709046596518',
    projectId: 'chuck-firebase',
    storageBucket: 'chuck-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKFVZMRtUCU54IDvL_iAieGR7mDQ2kCqU',
    appId: '1:709046596518:ios:9343d0385b9a595e70d567',
    messagingSenderId: '709046596518',
    projectId: 'chuck-firebase',
    storageBucket: 'chuck-firebase.appspot.com',
    iosClientId:
        '709046596518-2k98afj4a3c2lind8u5giehmghpnhkcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chuck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKFVZMRtUCU54IDvL_iAieGR7mDQ2kCqU',
    appId: '1:709046596518:ios:9343d0385b9a595e70d567',
    messagingSenderId: '709046596518',
    projectId: 'chuck-firebase',
    storageBucket: 'chuck-firebase.appspot.com',
    iosClientId:
        '709046596518-2k98afj4a3c2lind8u5giehmghpnhkcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chuck',
  );
}
